services:
  presence_api:
    build: .
    container_name: presence-service
    networks:
      - messenger
      - default
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=userpass
      - POSTGRES_DB=db
      - POSTGRES_HOST=presence-db
      - POSTGRES_PORT=5432
      - REDIS_HOST=presence-redis
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9094
    env_file:
      - .env
    depends_on:
      presence_redis:
        condition: service_started
      presence_db:
        condition: service_healthy
      # kafka:
      #   condition: service_healthy
    volumes:
      - .:/app

  presence_redis:
    image: redis:7-alpine
    container_name: presence-redis
    volumes:
      - presence_redis_data:/data
    command: redis-server --appendonly yes --notify-keyspace-events Ex
    networks:
      - default

  presence_db:
    image: postgres:17
    container_name: presence-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 2s
      timeout: 2s
      start_period: 10s  
      retries: 15
    volumes:
      - presence_db_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5435:5432"
    networks:
      - default


volumes:
  presence_redis_data:
  presence_db_data:

networks:
  messenger:
    external: true
