name: messenger

include:
  - infra/docker-compose.yml
  - user-service/docker-compose.yml
  - chat-service/docker-compose.yml
  - message-service/docker-compose.yml
  - presence-service/docker-compose.yml
  - api-gateway/docker-compose.yml

networks:
  messenger:
    external: true
