services:
  user_db:
      image: postgres:17
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
        interval: 2s
        timeout: 2s
        start_period: 10s  
        retries: 15
      volumes:
        - user_db:/var/lib/postgresql/data
      ports:
        - "5433:5432"
      env_file:
        - ./user-service/.env

  chat_db:
    image: postgres:17
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 2s
      timeout: 2s
      start_period: 10s  
      retries: 15
    volumes:
      - chat_db:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    env_file:
      - ./chat-service/.env

  mongodb:
    image: mongo:latest 
    container_name: my-mongo-container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    env_file:
      - ./message-service/.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASS

volumes:
  user_db:
  chat_db:
  mongo_data:
