services:
  db:
      image: postgres:17
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
        interval: 2s
        timeout: 2s
        start_period: 10s  
        retries: 15
      volumes:
        - postgres_data:/var/lib/postgresql/data
      ports:
        - "5433:5432"
      env_file:
        - ./.env

volumes:
  postgres_data:
