# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import protos.chat_pb2 as chat__pb2

GRPC_GENERATED_VERSION = '1.75.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in chat_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ChatStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUserChats = channel.unary_unary(
                '/chat.Chat/GetUserChats',
                request_serializer=chat__pb2.UserId.SerializeToString,
                response_deserializer=chat__pb2.MultipleChats.FromString,
                _registered_method=True)
        self.CreateGroupChat = channel.unary_unary(
                '/chat.Chat/CreateGroupChat',
                request_serializer=chat__pb2.CreateGroupChatRequest.SerializeToString,
                response_deserializer=chat__pb2.ChatId.FromString,
                _registered_method=True)
        self.GetOrCreatePrivateChat = channel.unary_unary(
                '/chat.Chat/GetOrCreatePrivateChat',
                request_serializer=chat__pb2.CreatePrivateChatRequest.SerializeToString,
                response_deserializer=chat__pb2.ChatId.FromString,
                _registered_method=True)
        self.UpdateChat = channel.unary_unary(
                '/chat.Chat/UpdateChat',
                request_serializer=chat__pb2.UpdateChatRequest.SerializeToString,
                response_deserializer=chat__pb2.ChatId.FromString,
                _registered_method=True)
        self.AddMembersToChat = channel.unary_unary(
                '/chat.Chat/AddMembersToChat',
                request_serializer=chat__pb2.AddMembersRequest.SerializeToString,
                response_deserializer=chat__pb2.ChatId.FromString,
                _registered_method=True)
        self.GetChatData = channel.unary_unary(
                '/chat.Chat/GetChatData',
                request_serializer=chat__pb2.ChatId.SerializeToString,
                response_deserializer=chat__pb2.ChatData.FromString,
                _registered_method=True)
        self.DeleteUserChat = channel.unary_unary(
                '/chat.Chat/DeleteUserChat',
                request_serializer=chat__pb2.DeleteUserFromChatRequest.SerializeToString,
                response_deserializer=chat__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.DeleteChat = channel.unary_unary(
                '/chat.Chat/DeleteChat',
                request_serializer=chat__pb2.ChatId.SerializeToString,
                response_deserializer=chat__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.GetLastReadMessage = channel.unary_unary(
                '/chat.Chat/GetLastReadMessage',
                request_serializer=chat__pb2.GetLastReadMessageRequest.SerializeToString,
                response_deserializer=chat__pb2.MessageId.FromString,
                _registered_method=True)


class ChatServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetUserChats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateGroupChat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrCreatePrivateChat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateChat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddMembersToChat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChatData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUserChat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteChat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLastReadMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUserChats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserChats,
                    request_deserializer=chat__pb2.UserId.FromString,
                    response_serializer=chat__pb2.MultipleChats.SerializeToString,
            ),
            'CreateGroupChat': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateGroupChat,
                    request_deserializer=chat__pb2.CreateGroupChatRequest.FromString,
                    response_serializer=chat__pb2.ChatId.SerializeToString,
            ),
            'GetOrCreatePrivateChat': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrCreatePrivateChat,
                    request_deserializer=chat__pb2.CreatePrivateChatRequest.FromString,
                    response_serializer=chat__pb2.ChatId.SerializeToString,
            ),
            'UpdateChat': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateChat,
                    request_deserializer=chat__pb2.UpdateChatRequest.FromString,
                    response_serializer=chat__pb2.ChatId.SerializeToString,
            ),
            'AddMembersToChat': grpc.unary_unary_rpc_method_handler(
                    servicer.AddMembersToChat,
                    request_deserializer=chat__pb2.AddMembersRequest.FromString,
                    response_serializer=chat__pb2.ChatId.SerializeToString,
            ),
            'GetChatData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChatData,
                    request_deserializer=chat__pb2.ChatId.FromString,
                    response_serializer=chat__pb2.ChatData.SerializeToString,
            ),
            'DeleteUserChat': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUserChat,
                    request_deserializer=chat__pb2.DeleteUserFromChatRequest.FromString,
                    response_serializer=chat__pb2.DeleteResponse.SerializeToString,
            ),
            'DeleteChat': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteChat,
                    request_deserializer=chat__pb2.ChatId.FromString,
                    response_serializer=chat__pb2.DeleteResponse.SerializeToString,
            ),
            'GetLastReadMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLastReadMessage,
                    request_deserializer=chat__pb2.GetLastReadMessageRequest.FromString,
                    response_serializer=chat__pb2.MessageId.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chat.Chat', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('chat.Chat', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Chat(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetUserChats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat.Chat/GetUserChats',
            chat__pb2.UserId.SerializeToString,
            chat__pb2.MultipleChats.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateGroupChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat.Chat/CreateGroupChat',
            chat__pb2.CreateGroupChatRequest.SerializeToString,
            chat__pb2.ChatId.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOrCreatePrivateChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat.Chat/GetOrCreatePrivateChat',
            chat__pb2.CreatePrivateChatRequest.SerializeToString,
            chat__pb2.ChatId.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat.Chat/UpdateChat',
            chat__pb2.UpdateChatRequest.SerializeToString,
            chat__pb2.ChatId.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddMembersToChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat.Chat/AddMembersToChat',
            chat__pb2.AddMembersRequest.SerializeToString,
            chat__pb2.ChatId.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChatData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat.Chat/GetChatData',
            chat__pb2.ChatId.SerializeToString,
            chat__pb2.ChatData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteUserChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat.Chat/DeleteUserChat',
            chat__pb2.DeleteUserFromChatRequest.SerializeToString,
            chat__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat.Chat/DeleteChat',
            chat__pb2.ChatId.SerializeToString,
            chat__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLastReadMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat.Chat/GetLastReadMessage',
            chat__pb2.GetLastReadMessageRequest.SerializeToString,
            chat__pb2.MessageId.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
