"""Add ChatMember table

Revision ID: 3b340e77d92e
Revises: 38b2b7979e59
Create Date: 2025-09-25 10:43:15.767619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b340e77d92e'
down_revision: Union[str, Sequence[str], None] = '38b2b7979e59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], name=op.f('fk__chat_members__chat_id__chats'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__chat_members'))
    )
    op.add_column('chats', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_column('chats', 'member1')
    op.drop_column('chats', 'member2')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('member2', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('chats', sa.Column('member1', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('chats', 'created_at')
    op.drop_table('chat_members')
    # ### end Alembic commands ###
