"""Add user avatar

Revision ID: 74b4ddb4d1b2
Revises: a3ab790cc5fd
Create Date: 2025-12-02 17:15:54.729796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74b4ddb4d1b2'
down_revision: Union[str, Sequence[str], None] = 'a3ab790cc5fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_replication', sa.Column('avatar', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_replication', 'avatar')
    # ### end Alembic commands ###
