"""Add nullable cols for ChatModel

Revision ID: 809ae4ff4212
Revises: c2801a399205
Create Date: 2025-10-08 14:09:36.109776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '809ae4ff4212'
down_revision: Union[str, Sequence[str], None] = 'c2801a399205'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('avatar', sa.String(), nullable=True))
    op.add_column('chats', sa.Column('last_message', sa.String(), nullable=True))
    op.add_column('chats', sa.Column('last_message_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'last_message_at')
    op.drop_column('chats', 'last_message')
    op.drop_column('chats', 'avatar')
    # ### end Alembic commands ###
