"""Add type enum

Revision ID: a3ab790cc5fd
Revises: f9e21fb146a2
Create Date: 2025-11-28 22:48:45.498596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from src.enums.adapter import IntEnumType
from src.enums.enums import ChatTypeEnum


# revision identifiers, used by Alembic.
revision: str = 'a3ab790cc5fd'
down_revision: Union[str, Sequence[str], None] = 'f9e21fb146a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('chat_type', IntEnumType(ChatTypeEnum), nullable=False))
    op.alter_column('chats', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('uq__chats__name'), 'chats', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq__chats__name'), 'chats', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('chats', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('chats', 'chat_type')
    # ### end Alembic commands ###
