"""Add unique constraint for ChatMembers

Revision ID: c2801a399205
Revises: dd6c3b264753
Create Date: 2025-09-25 21:10:26.880549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2801a399205'
down_revision: Union[str, Sequence[str], None] = 'dd6c3b264753'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_chat_user_uc', 'chat_members', ['chat_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_chat_user_uc', 'chat_members', type_='unique')
    # ### end Alembic commands ###
