"""Add foreign key

Revision ID: d25aa5b57860
Revises: 941e459b3493
Create Date: 2025-10-11 13:24:38.552655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd25aa5b57860'
down_revision: Union[str, Sequence[str], None] = '941e459b3493'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk__chat_members__user_id__users_replication'), 'chat_members', 'users_replication', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk__chat_members__user_id__users_replication'), 'chat_members', type_='foreignkey')
    # ### end Alembic commands ###
