"""Add uniqie constr for ChatModel

Revision ID: dd6c3b264753
Revises: 3b340e77d92e
Create Date: 2025-09-25 10:50:16.722751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd6c3b264753'
down_revision: Union[str, Sequence[str], None] = '3b340e77d92e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chats', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(op.f('uq__chats__name'), 'chats', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq__chats__name'), 'chats', type_='unique')
    op.alter_column('chats', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
