"""Add new col to ChatMembersModel

Revision ID: f9e21fb146a2
Revises: 7874e0252517
Create Date: 2025-10-18 13:38:58.510742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9e21fb146a2'
down_revision: Union[str, Sequence[str], None] = '7874e0252517'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_members', sa.Column('last_read_message_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_members', 'last_read_message_id')
    # ### end Alembic commands ###
