"""Add unique constraint for UserModel

Revision ID: ba2d4cbf6f28
Revises: 0fb12e31d583
Create Date: 2025-10-15 17:04:53.605129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba2d4cbf6f28'
down_revision: Union[str, Sequence[str], None] = '0fb12e31d583'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__users__username'), table_name='users')
    op.create_index(op.f('ix__users__username'), 'users', ['username'], unique=False)
    op.create_unique_constraint(op.f('uq__users__username_is_active'), 'users', ['username', 'is_active'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq__users__username_is_active'), 'users', type_='unique')
    op.drop_index(op.f('ix__users__username'), table_name='users')
    op.create_index(op.f('ix__users__username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###
