# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: message.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"G\n\x12SendMessageRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x0f\n\x07\x63hat_id\x18\x03 \x01(\x05\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\t\"i\n\x13SendMessageResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x12\n\nmessage_id\x18\x02 \x01(\t\x12.\n\ncreated_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"4\n\x10SubscribeRequest\x12\x0f\n\x07\x63hat_id\x18\x01 \x01(\x05\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\"\x92\x01\n\x07Message\x12\x12\n\nmessage_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63hat_id\x18\x02 \x01(\x05\x12\x0f\n\x07user_id\x18\x03 \x01(\x05\x12\x10\n\x08username\x18\x04 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x05 \x01(\t\x12.\n\ncreated_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"(\n\x15GetAllMessagesRequest\x12\x0f\n\x07\x63hat_id\x18\x01 \x01(\x05\"4\n\x16GetAllMessagesResponse\x12\x1a\n\x08messages\x18\x01 \x03(\x0b\x32\x08.Message2\xc7\x01\n\x0eMessageService\x12:\n\x0bSendMessage\x12\x13.SendMessageRequest\x1a\x14.SendMessageResponse\"\x00\x12\x34\n\x11SubscribeMessages\x12\x11.SubscribeRequest\x1a\x08.Message\"\x00\x30\x01\x12\x43\n\x0eGetAllMessages\x12\x16.GetAllMessagesRequest\x1a\x17.GetAllMessagesResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENDMESSAGEREQUEST']._serialized_start=50
  _globals['_SENDMESSAGEREQUEST']._serialized_end=121
  _globals['_SENDMESSAGERESPONSE']._serialized_start=123
  _globals['_SENDMESSAGERESPONSE']._serialized_end=228
  _globals['_SUBSCRIBEREQUEST']._serialized_start=230
  _globals['_SUBSCRIBEREQUEST']._serialized_end=282
  _globals['_MESSAGE']._serialized_start=285
  _globals['_MESSAGE']._serialized_end=431
  _globals['_GETALLMESSAGESREQUEST']._serialized_start=433
  _globals['_GETALLMESSAGESREQUEST']._serialized_end=473
  _globals['_GETALLMESSAGESRESPONSE']._serialized_start=475
  _globals['_GETALLMESSAGESRESPONSE']._serialized_end=527
  _globals['_MESSAGESERVICE']._serialized_start=530
  _globals['_MESSAGESERVICE']._serialized_end=729
# @@protoc_insertion_point(module_scope)
