from abc import ABC
from datetime import datetime

from src.models import ChatModel, ChatMemberModel, UserReplicaModel
from src.dto.chat import CreateGroupDTO, UpdateGroupDTO

class IChatRepository(ABC):
    async def get(self, id: int) -> ChatModel | None: ...        
     
    async def get_by_user_id(self, user_id: int) -> ChatModel: ... 
     
    async def get_chat_member(self, chat_id: int, user_id: int) -> ChatMemberModel | None: ...
     
    async def get_private(self, current_user: int, target_user: int) -> ChatModel | None: ...
     
    async def create_group(self, data: CreateGroupDTO) -> ChatModel: ...
     
    async def create_private(self, current_user: int, target_user: int) -> ChatModel: ...       
     
    async def update(self, chat: ChatModel, data: UpdateGroupDTO) -> ChatModel: ...
     
    async def update_last_read_message(
        self, 
        chat_member: ChatMemberModel, 
        last_read_message_id: str
    ) -> ChatMemberModel: ...
     
    async def add_members(self, chat: ChatModel, members: list) -> ChatModel: ...   
     
    async def update_chat_last_message(
        self, 
        chat: ChatModel, 
        last_message: str, 
        last_message_at: datetime
    ) -> None: ...
        
    async def delete(self, chat_id: int) -> int: ...        
     
    async def delete_user_chats(self, user_id: int) -> int: ...        
     
    async def delete_user_from_chat(self, user_id: int, chat_id: int) -> int: ...
    
    
class IUserRepository(ABC):
    async def get(self, id: int, is_active: bool = True) -> UserReplicaModel | None: ...
    
    async def get_multiple(self, ids: list, is_active: bool = True) -> list[UserReplicaModel]: ...
    
    async def upsert(self, data: dict) -> None: ...
    
    async def deactivate(self, user_id: int) -> None: ...


