from abc import ABC
from typing import List

from src.models import ChatModel, ChatMemberModel, UserReplicaModel
from src.dto.chat import *
from src.schemas.message import MessageData
from src.schemas.user import UserData

class IChatService(ABC):
    async def get(self, id: int) -> ChatModel: ...

    async def get_user_chats(self, user_id: int) -> List[ChatModel]: ...

    async def get_multiple_users(self, members: list) -> List[UserReplicaModel]: ...
    
    async def get_chat_member(self, chat_id: int, user_id: int) -> ChatMemberModel: ...
    
    async def get_or_create_private(self, current_user: int, target_user: int) -> ChatModel: ...

    async def create_group(self, data: CreateGroupDTO) -> ChatModel: ...

    async def update(self, data: UpdateGroupDTO) -> ChatModel: ...
    
    async def update_last_read_message(
        self, 
        chat_id: int, 
        user_id: int, 
        last_read_message_id: str
    ) -> ChatMemberModel: ...

    async def add_members(self, chat_id: int, members: list) -> ChatModel: ...

    async def update_chat_last_message(self, data: MessageData) -> None: ...

    async def delete(self, chat_id: int) -> str: ...

    async def delete_user_from_chat(self, user_id: int, chat_id: int) -> str: ...


class IUserService(ABC):
    async def get(self, user_id: int) -> UserReplicaModel: ...

    async def get_multiple(self, ids: list[int]) -> tuple[list[UserReplicaModel], list[UserReplicaModel]]: ...

    async def create_or_update(self, data: UserData) -> None: ...

    async def deactivate(self, id: int) -> None: ...
